spring.application.name=heros-journey
# Google GenAI settings
spring.ai.google.genai.api-key=AIzaSyBJ5356lZ9xky9WDdX951Vbmkk9zCfzgec
# Chat options
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.7